### ISSUE TITLE
与 Typecho 1.0 不兼容？

### ISSUE THREAD

**Issue by JokerQyou** [visamz/GravatarCache#1]
在 Typecho 1.0 上测试。首先是文件名不对？貌似 Typecho 是要求插件主文件名必须是 Plugin.php 。
修改之后启用直接报 500 错误。

**Comment by visamz** [comment]
嗯，抱歉，暂时还没来得及升级，解决方法是暂时禁用。等我升级发布再用吧~

**Comment by JokerQyou** [comment]
嗯。谢谢了

**Comment by banrikun** [comment]
直接把文件丢plugin目录下就可以用了...
不过感觉逻辑上存在点问题的说...是先缓存再访问，如果页面图片很大的话，好久才能点开页面…

**Comment by visamz** [comment]
我升级测试发现,typecho 1.0 是可以正常使用的。Typecho 的插件形式有两种：单文件 和 文件夹，如果 是文件夹，那必须 有 plugin.php  这个文件。
@banrikun  你提的这个问题确实存在，就是如果已经存在评论的文章，初次使用时 因为需要把头像下载下来，所以如果 评论比较多，初次打开是比较缓慢。
